name: Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-22.04'

    env:
      APP_NAME: 'EverySingleMinute'
      JAVA_VERSION: '21'
      ANDROID_SDK_VERSION: '8512546'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}

      # - name: Setup Android SDK
      #   uses: android-actions/setup-android@v3
      #   with:
      #     cmdline-tools-version: ${{ env.ANDROID_SDK_VERSION }}

      - name: Build APK
        run: ./gradlew --no-daemon assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.APP_NAME }}.apk
          path: app/build/outputs/apk/debug/app-debug.apk
